### ISSUE TITLE
[META] Merge in anything from 7.x-2.x that doesn't break BC

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/privatemsg#36]
Here's a diff: https://github.com/backdrop-contrib/privatemsg/compare/7.x-1.x...7.x-2.x

Lots of minor improvements such as spelling, using `#attached`, create a base test class, etc. The minor things won't need separate issues, but bigger ones such as new functions, would.

- [x] Email notification levels. pm_email_notify (notification levels)
- [x] Track more settings per user not just disabled status. pm_settings (rename to pm_entity_settings)
- [x] Track reply-to's. add a reply_to_mid column to pm_message
- [x] report messages to Akismet (based on the Mollom version)
- [x] OG integration
- [x] per role write privagemsg permission
- [x] improve cron handling
- [ ] theme improvements - break up into smaller functions
- [ ] privatemsg_get_headers - Issue #1022404 by Berdir, te-brian: Added drag and drop sorting for list display fields and replaced header theme functions with a hook.
- [x] by Berdir: Fixed subject is changed when answering to a thread with a tokenized subject. 5dea97d34000fe87df4b2b699418a6d934d4fd9b
- [ ] Do not hardcode #maxlength (issue ID?)
